modLoader = "javafml"
loaderVersion = "[45,)"
license = "Unlicense"

[[mods]]
modId = "xibao"
version = "${version}"
displayName = "XiBao-Architectured"
credits = "TeaCon, IzzelAliz"
authors = "ThinkingStudio, TexTrue"
description = '''
Xibao's Architectury port
'''
#logoFile = ""

[[dependencies.xibao]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xibao]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.xibao]]
modId = "architectury"
mandatory = true
versionRange = "[9,)"
ordering = "AFTER"
side = "BOTH"